### ISSUE TITLE
linphone的电话会议

### ISSUE THREAD

**Issue by deboLing** [ddssingsong/VoipLibrary#1]
基于linphone的电话会议用什么方式实现呢？ 
目前据我所了解，
一种是所有终端拨打一个特定号码，比如3000，大家就进入电话会议状态了。
另一种，从linphone源码中看到LinphoneCore文件中有关于会议室的创建，加入，退出。但是不知道这种方式如何实现。
请问大神有什么优雅的方式来实现呢？

**Comment by ddssingsong** [comment]
设置20000-30000为会议房间号，然后加进去 就可以的，服务器使用freeswitch之类的进行混音啥的
